version: '2.1'

services:
  nginx:
    image: openresty/openresty:alpine
    #image: nginx
    ports:
      - "8080:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - ./confd:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro